const US_NAME_ZH: Record<string, string> = {
  AAPL: "苹果",
  NVDA: "英伟达",
  MSFT: "微软",
  GOOGL: "谷歌",
  GOOG: "谷歌",
  AMZN: "亚马逊",
  META: "Meta",
  TSLA: "特斯拉",
  NFLX: "奈飞",
  AVGO: "博通",
  AMD: "超威半导体",
  JPM: "摩根大通",
  V: "Visa",
  MA: "万事达",
  JNJ: "强生",
  WMT: "沃尔玛",
  UNH: "联合健康",
  XOM: "埃克森美孚",
  ORCL: "甲骨文",
  KO: "可口可乐",
  PEP: "百事",
  MCD: "麦当劳",
  NKE: "耐克",
  INTC: "英特尔",
  CSCO: "思科",
  ADBE: "奥多比",
  CRM: "赛富时",
  QCOM: "高通",
  TXN: "德州仪器",
  CAT: "卡特彼勒",
  BA: "波音",
  DIS: "迪士尼",
  PFE: "辉瑞",
  MRK: "默沙东",
  ABBV: "艾伯维",
  COST: "开市客",
  TMO: "赛默飞世尔",
  HD: "家得宝",
  PG: "宝洁",
  CVX: "雪佛龙",
  BAC: "美国银行",
  GS: "高盛",
  MS: "摩根士丹利",
  IBM: "IBM",
  GE: "通用电气",
  F: "福特汽车",
  GM: "通用汽车",
  UBER: "优步",
  ABNB: "爱彼迎",
  COIN: "Coinbase",
  PLTR: "Palantir",
  SPY: "标普500 ETF",
  QQQ: "纳斯达克100 ETF",
  DIA: "道琼斯 ETF",
  VIXY: "VIX 波动率 ETF",
  XLK: "科技",
  XLF: "金融",
  XLV: "医疗保健",
  XLE: "能源",
  XLY: "非必需消费",
  XLI: "工业",
};

export function usNameZh(name: string | null | undefined, code?: string | null): string {
  const symbol = (code || "").trim().toUpperCase();
  if (symbol && US_NAME_ZH[symbol]) return US_NAME_ZH[symbol];
  return (name || "").trim() || symbol;
}

export function usTypeZh(type: string | null | undefined): string {
  if (type === "Common Stock") return "普通股";
  return type || "美股";
}
